[bootstrap.packages."macos-app:rayvy"]
version = "0.3.2"
url = "https://github.com/Mkamono/rayvy/releases/download/v{{version}}/Rayvy-{{version}}-arm64.zip"
sha256 = "54f3d9554263d8128f5c526b53ee78d56d7a7089479f40867431a066f265c8e6"
artifact = "Rayvy.app"
os = "macos/arm64"
